name: mobile_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.3
  flutter:
    sdk: flutter
  geolocator: ^8.2.1
  fluttertoast:
  http: ^0.13.4
  flutter_secure_storage: ^5.0.2
  flutter_dotenv: ^5.0.2
  flutter_spinkit: ^5.1.0
  intl_phone_number_input: ^0.7.0+2
  country_list_pick: ^1.0.1+5


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - .env.development
    - .env.production
